# Generated by Django 3.1.7 on 2021-03-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='texts',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
