# Generated by Django 3.1.7 on 2021-03-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210326_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.CharField(default=1, max_length=22),
            preserve_default=False,
        ),
    ]
