# Generated by Django 3.1.7 on 2021-03-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_tasks_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='texts',
            new_name='TO_DO',
        ),
    ]
