# Generated by Django 3.1.7 on 2021-03-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210326_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='TO_DO',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
